### ISSUE TITLE
Error in Collector

### ISSUE THREAD

**Issue by SegaPro79** [shackrat/trackdirect#1]
There seems to be an error with the collector.

The data is either not saved correctly or sorted incorrectly.

Many of the stations no longer appear at all - beacons do not arrive.

Some stations still send beacons and are also shown on the map. However, after reloading the page, they have disappeared again.

The error is reproducible and only occurs when using the new bins and scripts under "server".

I suspect a bug in the collector or in the wsserver.

**Comment by SegaPro79** [comment]
The problem is obviously in "TrackDirectDataCollector.py" - when using this file, the raw data is no longer stored in the database for most stations.

A recent beacon is shown on the map at some stations, but is not visible in the raw data.

**Comment by shackrat** [comment]
What you describe indicates the collector is not saving data.  Please check the source ID's defined in your trackdirect.ini for each collector.  ID's greater than 5 are ignored by the collector in my modified code.  If you have added additional sources, please let me know the ID's assigned.

**Comment by SegaPro79** [comment]
I configured 3 sources.

The first is APRS-IS with Source ID 1

The second is CWOP with SID 2

The third is OGN with SID 5

Three instances of APRSC are running on the server. Therefore, the collectors use the local instances.

Up until the August release, everything is going really perfectly. After that, something fundamental seems to have changed.

Here is the config:

[collector0]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               host="127.0.0.1"                                                                                                                                                                                                 port_full="10152"                                                                                                                                                                                                port_filtered="14580"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                          source_id="1"  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      callsign="xxxxxx"                                                                                                                                                                                             passcode="xxxxx"                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                           numbers_in_batch="30"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      frequency_limit="15" 
                                                                                                                                                                                            save_fast_packets="0"                                                                                                                                                                                            detect_duplicates="0"                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                           error_log="xxxxxxxxxxxx"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

[collector1]                                                                                                                                                                                                     
                                                                                                                                                                                                               source_id="2"                                                                                                                                                                                                    host="127.0.0.1"                                                                                                                                                                                                 port_full="10153"                                                                                                                                                                                                port_filtered="14581"                                                                                                                                                                                                                                                                                                                                                                                                             callsign="xxxxxxx"                                                                                                                                                                                             passcode="xxxxxxx"                                                                                                                                                                                                                                                                                                                                                                                                                  numbers_in_batch="30"                                                                                                                                                                                            frequency_limit="15"                                                                                                                                                                                             save_fast_packets="0"                                                                                                                                                                                            detect_duplicates="1"                                                                                                                                                                                                                                                                                                                                                                                                             error_log="xxxxxxxxxxxxx"     

[collector2]                                                                                                                                                                                                                                                                                                                                                                                                                      source_id="5"                                                                                                                                                                                                    host="127.0.0.1"                                                                                                                                                                                                 port_full="10154"                                                                                                                                                                                                port_filtered="14582"                                                                                                                                                                                                                                                                                                                                                                                                             callsign="xxxxxxx"                                                                                                                                                                                             passcode="xxxxxxx"                                                                                                                                                                                                                                                                                                                                                                                                                  numbers_in_batch="30"                                                                                                                                                                                            frequency_limit="20"                                                                                                                                                                                             save_fast_packets="0"                                                                                                                                                                                            detect_duplicates="1"                                                                                                                                                                                                                                                                                                                                                                                                             error_log="xxxxxxxx

**Comment by shackrat** [comment]
Thanks for the config.  That was helpful.   I have a fix posted.  Was a stupid mistake on my part last month when I committed the collector code to GitHub.  Let me know if that fixes it.

**Comment by SegaPro79** [comment]
Now it's running perfectly.

Small change and big effect. :)

Thanks for the quick help. Great work, keep it up.

I love this fork.

**Comment by shackrat** [comment]
Awesome.  Glad that fixed it and to hear you enjoy the fork.  There's another huge update coming soon!
